### ISSUE TITLE
Migrating existing mediawiki user accounts

### ISSUE THREAD

**Issue by AkBKukU** [Digitalroot/MediaWiki_PHPBB_Auth#52]
I'm looking at adding a forum to a wiki and like the idea of having a single login. I was wondering how this extension handles migrating existing user accounts on mediawiki so users keep their edit history. I didn't see anything about it in the readme here or on the mediawiki extension page for it and figured I should just ask.

**Comment by cpeel** [comment]
As long as the forum usernames names map (either directly or via the `UseWikiProfile` feature) to the existing MediaWiki usernames, they will be treated as the same wiki account and retain their edit history, etc. Because phpBB usernames and MediaWiki usernames have different restrictions, using the [`UseWikiProfile` feature](https://github.com/Digitalroot-Technologies/MediaWiki_PHPBB_Auth#custom-phpbb-to-mediawiki-username-translation) to explicitly map them together is the recommended path for existing MediaWiki installations.

**Comment by AkBKukU** [comment]
Ah, that sounds good then. Thanks!
